# -*- coding: utf-8 -*-
"""10year_StockData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XGapZ7Enn7s_967PQvkncANQiz1J6ECX
"""

!pip install yfinance openpyxl

import yfinance as yf
import pandas as pd
from google.colab import files

indices = {
    'Nifty_50': '^NSEI',       # Nifty 50 (India)
    'Sensex': '^BSESN',        # SENSEX (India)
    'SP500': '^GSPC',          # S&P 500 (US)
    'NASDAQ': '^IXIC',         # NASDAQ (US)
    'Nikkei_225': '^N225',     # Nikkei 225 (Japan)
    'Dow_Jones': '^DJI',       # Dow Jones Industrial Average (US)
}

for index_name, ticker in indices.items():
    try:

        data = yf.Ticker(ticker).history(period="10y")


        data.index = data.index.tz_localize(None)


        excel_filename = f"{index_name}_10y_data.xlsx"
        data.to_excel(excel_filename)


        files.download(excel_filename)

        print(f"Data for {index_name} downloaded and saved as {excel_filename}")
    except Exception as e:
        print(f"Failed to download data for {index_name}: {e}")


data.head()